---
new_page_extension: md
auto_deploy: true
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Pages
- type: document
  path: content/about/_index.md
  label: About
- type: document
  path: content/contact/_index.md
  label: Contact
- type: heading
  label: Blog
- type: directory
  path: content/blog/hub-updates
  label: Blog Posts
  create: all
  match: "**/*"
- type: directory
  path: content/blog/events
  label: Events
  create: all
  match: "**/*"
- type: heading
  label: Other Things
- type: directory
  path: content/lists/member_startups
  label: Member Startups
  create: all
  match: "**/*"
upload_dir: ''
public_path: ''
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  preview_command: hugo -E -F -D -b $DEPLOY_URL -d public
  publish_command: hugo
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.54.0
  publish_env:
  - HUGO_ENV=production
  - HUGO_VERSION=0.54.0
  preview_output_directory: public
  output_directory: public
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.54.0
